
const TOKEN_CONTRACT_ADDRESS = process.env.TOKEN_CONTRACT_ADDRESS || '0x0';

const CHILLISWAP_CONTRACT_ADDRESS = process.env.CHILLISWAP_CONTRACT_ADDRESS || '0x0';

const CHILLISWAP_CONTRACT_ADDRESS_RINKEBY = process.env.CHILLISWAP_CONTRACT_ADDRESS_RINKEBY || '0x0';

const CHILLISWAP_CONTRACT_ADDRESS_MUMBAI = process.env.CHILLISWAP_CONTRACT_ADDRESS_MUMBAI || '0x0';

const MARKET_CONTRACT_ADDRESS = process.env.MARKET_CONTRACT_ADDRESS || '0x0';

const CHILLINFT_CONTRACT_ADDRESS = process.env.CHILLINFT_CONTRACT_ADDRESS || '0x0';


module.exports = {
    TOKEN_CONTRACT_ADDRESS,
    CHILLISWAP_CONTRACT_ADDRESS,
    MARKET_CONTRACT_ADDRESS,
    CHILLINFT_CONTRACT_ADDRESS,
    CHILLISWAP_CONTRACT_ADDRESS_RINKEBY,
    CHILLISWAP_CONTRACT_ADDRESS_MUMBAI
}
